service: producer-kakfa-node

provider:
  name: kubeless
  runtime: nodejs8
  namespace: kubeless
  environment :
    FAKE_KRYTPO_URL: 'http://localhost:3000/producer'
    KAFKA_URL: 'localhost:9092'

package:
  excludeDevDependencies: true
  exclude:
    - test/**
    - node_modules/**

functions:
  fake-krypto:
    handler: producer.producerKafka
    events:
      - http : POST producer

custom:
  stage: 'dev'
  dev:
    FAKE_KRYTPO_URL: 'http://localhost:3000/producer'
    KAFKA_URL: 'localhost:9092'
  docker :
    FAKE_KRYTPO_URL: 'http://localhost:3000/producer'

plugins:
  - serverless-offline
